repo_url: https://github.com/2418071565/2418071565.github.io.git
site_name: NBU ACM

copyright: "CopyRight &copy CYB"
edit_uri: edit/master/docs

nav:
  - 主页: index.md
  - 算法: 
    - 二分:
      - 整数二分: Algorithm/BinarySearch/Integer/Integer.md
    - 动态规划:
      - 背包问题: Algorithm/DP/Knapsack/Knapsack.md
    - 倍增: Algorithm/BinaryLifting/BinaryLifting.md
    - 排序: 
      - 简介: Algorithm/Sort/Sort.md
      - 冒泡排序: Algorithm/Sort/BubbleSort/Bubble.md
  - 字符串:
    - 字典树: String/Trie/Trie.md
    - 字符串哈希: String/StringHash/StringHash.md
    - KMP: String/KMP/KMP.md
    - 马拉车: String/Manacher/Manacher.md
  - 数据结构:
    - 堆: 
      - 二叉堆: DS/Heap/BinHp.md
    - 哈希表: DS/HTable/HTable.md
    - 并查集: DS/UnionFind/UF.md
    - 分块: DS/Block/Block.md
    - 树状数组: 
      - 树状数组: DS/BIT/BIT.md
      - 二维树状数组: DS/BIT/2_BIT.md
    - 平衡搜索树: 
      - Splay: DS/Splay/Splay.md
      - B 树: DS/BTree/BTree.md
      - AVL: DS/AVLTree/AVL.md
    - 线段树: 
      - 基础线段树: DS/SegTr/SegTr.md
      - 吉如一线段树: DS/SegTr/JRYSegTr.md
  - 图论: 
    - 图的存储: Graph/StorageOfGraphs/Storage.md
    - 拓朴排序: Graph/TopoSort/Topo.md
    - 树: 
      - 树基础: Graph/Tree/Basic/Basic.md
      - 最小生成树: Graph/Tree/MST/MST.md
  - 数学:
    - 计算几何:
      - 二维计算几何基础: Math/Geometry/2DGeometry/2D.md
      - 凸包: Math/Geometry/ConvexHull/CH.md
    - 数论:
      - 数论基础: Math/NumberTheory/Fd.md
      - 快速幂: Math/NumberTheory/Qpow/qpow.md
      - 乘法逆元: Math/NumberTheory/Inv/Inv.md
    - 数值计算:
      - 牛顿迭代法: Math/Numerical/NtsMethod/Nt.md
      - 快速平方根倒数算法: Math/Numerical/QSqrt/QSqrt.md
  - 问题总结:
    - 整数拆分: UsualQ/IntPartition/IntPartition.md
    - 区间最大子段和: UsualQ/MaxSumOfSub/MaxSumOfSub.md
    - 暑期集训: UsualQ/SummerTraining/SumTraining.md





theme:
  name: material
  palette: 
    primary: white
  language: zh
  custom_dir: overrides/
  favicon: Web_icon.svg
  features: 
    - content.code.select
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.instant.progress
    - navigation.footer
    - content.tabs.link
    - search.highlight
  icon:
    admonition:
      code: material/note-alert
    logo: Web_icon
    repo: repo_icon



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
    
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/2418071565
    - icon: fontawesome/solid/paper-plane
      link: mailto:idlecyb@163.com


